name: CI

on:
  repository_dispatch:
    types: [contents_update]

jobs:
  FrontDeploy:
    name: FrontDeploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: develop
        
    - name: setup Node
      uses: actions/setup-node@v1
      with: 
        node-version: 12.x
        registry-url: 'https://registry.npmjs.org'
    - name: Install Dependencies
      run: yarn && yarn build && yarn export
      # ↑ buildが違うコマンドなら、適宜変更して下さい
    - name: deployConfig
      run: |
        yarn deployset:dev

    - name: deploy to Firebase Hosting
      run: |
        yarn deploy --token="${{ secrets.FIREBASE_TOKEN }}" --only hosting:dev
